// <auto-generated />
namespace CPC2020_2_Lab4.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class Dodanotabelezużytkownikami : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Dodanotabelezużytkownikami));
        
        string IMigrationMetadata.Id
        {
            get { return "202012171932088_Dodano tabele z użytkownikami"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
